### ISSUE TITLE
Other chords are not working

### ISSUE THREAD

**Issue by ljfreelancer88** [Svish/Transposer#1]
Hi! during my initial used. Cmin7(other form for Cm7) and CM7(other form for Cmaj7) is not working. C2, Csus2, Csus4, Cadd4, C5, C6, C7, Caug, Cdim, C9 is fine.

Thanks BTW.

**Comment by Svish** [comment]
I'm not a musician, so I don't really "speak music".

Could you share the original key, the target key, and a chord line with the problematic chords?

What exactly is "not working"? Is the chord line not transposed at all, or are certain chords transposed incorrectly?

**Comment by ljfreelancer88** [comment]
Let say, this is my Intro...

`F   C   Bb2  CM7`  This line won't transpose because CM7 is not recognized i think?

`F   C   Bb2  Cmaj7`  But if I use the Cmaj7 which is the other form of CM7, it will transpose to desired Key

One more thing, If I try to add an indication like `(Break)` near the chord. This will not also work or transpose.
```
    G         G7  (Break)
Amazing Grace.
```

**Comment by Svish** [comment]
Here's the regex which matches chords:  
https://github.com/Svish/Transposer/blob/master/src/Geekality/Transposer.php#L323

The "rule" in the current code is that a line is only considered a chord line if it's able to consume the whole line using that regex. So anything on the chord line which doesn't match the regex makes the line be considered a text line instead.

My first suggestion is to just use `Cmaj7` instead, and to put `(Break)` on a separate line, like I do with `(chorus)` in the [sample](https://github.com/Svish/Transposer/blob/master/sample/sample.txt), since that would make it work.

If that won't work for you, feel free to try make adjustments and create a PR.

The first issue could possibly be fixed just by making the regex case-insensitive, but not sure if that could potentially cause non-chord lines to be considered chord-lines by accident. 

The second would possibly need a bit more work. Not sure. Many years since I wrote this, and not even 100% sure how it works myself anymore. 🤷‍♂️😛

**Comment by pedropolidoro** [comment]
https://gist.github.com/pedropolidoro/51b231f5433c50a1f73bb2ba020c7148
https://gist.github.com/pedropolidoro/e9bac748c7970d91ecb688dd57506a92
