### ISSUE TITLE
RegEx is not picking up the b5

### ISSUE THREAD

**Issue by ljfreelancer88** [Svish/Transposer#3]
Hi, sorry to bother you. Maybe you can help me to point the issue. Because RegEx is not picking up `b5` on the chord. :) I tried to group using `[m7b5]` but it's not efficient because it will mess up the other.

I tried to check all here https://regex101.com/r/7XN2kE/4

**Comment by ljfreelancer88** [comment]
I think, I found the answer. I put `[m7b]` way down to the last. But I'm not sure, if that's a "hack" approach.

```bash
|sus2|sus|[m7b])*)
```

**Comment by Svish** [comment]
@ljfreelancer88 The chord regex is case-sensitive, so if you change it to `B5`, rather than `b5`, then I think it should work.

And not sure if you're aware, but `[m7b]` is a character group, so it will match any of those letters in any order, which is probably not what you'd want.

So, to sum up: Either change to upper-case `B`, or make the regex case-insensitive by adding the `i` modifier after the `%u` in the regex.
